// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmuJftIhQigJyM18GcHcZDOOEpbDnrnn0',
    appId: '1:949655569333:web:ca0410b1f9fe029f70cffc',
    messagingSenderId: '949655569333',
    projectId: 'dormcare-app',
    authDomain: 'dormcare-app.firebaseapp.com',
    storageBucket: 'dormcare-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdqdERlaY-bE96zX1NNyuL3ArmxeDBlaI',
    appId: '1:949655569333:android:00346d0e9a98b05370cffc',
    messagingSenderId: '949655569333',
    projectId: 'dormcare-app',
    storageBucket: 'dormcare-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Zt1-2bejVgP0rK5jyNR4Ejl-cHkPPJA',
    appId: '1:949655569333:ios:c53bfc67f3a70bc270cffc',
    messagingSenderId: '949655569333',
    projectId: 'dormcare-app',
    storageBucket: 'dormcare-app.firebasestorage.app',
    iosBundleId: 'com.example.dormcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1Zt1-2bejVgP0rK5jyNR4Ejl-cHkPPJA',
    appId: '1:949655569333:ios:c53bfc67f3a70bc270cffc',
    messagingSenderId: '949655569333',
    projectId: 'dormcare-app',
    storageBucket: 'dormcare-app.firebasestorage.app',
    iosBundleId: 'com.example.dormcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmuJftIhQigJyM18GcHcZDOOEpbDnrnn0',
    appId: '1:949655569333:web:fe84245da64e89b470cffc',
    messagingSenderId: '949655569333',
    projectId: 'dormcare-app',
    authDomain: 'dormcare-app.firebaseapp.com',
    storageBucket: 'dormcare-app.firebasestorage.app',
  );
}
